[versions]
kotlin = "2.2.10"
nexus-publish = "2.0.0"

[libraries]
nexus-publish = { module = "io.github.gradle-nexus.publish-plugin:io.github.gradle-nexus.publish-plugin.gradle.plugin", version.ref = "nexus-publish" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

[bundles]

[plugins]
vanniktech-mavenPublish = { id = "com.vanniktech.maven.publish", version = "0.31.0" }
